image: atlassian/default-image:3

definitions:
  services:
    docker:
      memory: 2048

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - docker
        script:
          - docker build -f apps/Dockerfile -t $DOCKER_REGISTRY/xqtiv-service-python:latest -t $DOCKER_REGISTRY/xqtiv-service-python:${BITBUCKET_COMMIT:0:7} --build-arg BUILDKIT_INLINE_CACHE=1 .
          - docker save $DOCKER_REGISTRY/xqtiv-service-python:latest > docker/xqtiv-service-python.tar
        artifacts:
          - docker/xqtiv-service-python.tar

  branches:
    development:
      - step:
          name: Deploy to Development
          deployment: development
          script:
            - docker-compose --env-file .env.development up -d

  # pull-requests:
  #   "**":
  #     - step:
  #         name: Build and Test PR
  #         script:
  #           # - docker build -f apps/Dockerfile -t xqtiv-api:test .
  #           # - docker run --rm xqtiv-api:test python -m pytest tests/
