services:
  ats-home-craft-python-service:
    container_name: ats-home-craft-python-service
    restart: always
    image: appscrip007/ats-home-craft-python-service:latest
    networks:
      - ats_home_craft_network
    ports:
      - "5000:5000"
    env_file:
      - .env
    logging:
      options:
        max-size: "1m"
        max-file: "3"

networks:
  ats_home_craft_network:
    external: true
