"""
Audit Logger Module

This module provides a comprehensive audit logging system for tracking user actions
and data changes in the application. It implements a queue-based asynchronous
logging system with database persistence and audit chain integrity.

The module includes:
- AuditEventData: Data class for structured audit event information
- AuditLogger: Main audit logging class with queue processing and database storage
- audit_logger: Singleton instance for application-wide use

Features:
- Asynchronous queue-based processing for performance
- Audit chain integrity with hash linking
- Configurable retention periods based on data classification
- Comprehensive error handling and retry logic
- Support for multiple data classifications (PII, PHI, financial, etc.)

Author: Generated by AI Assistant
Date: 2024
"""

# apps/user_service/app/dependencies/audit_logs/audit_logger.py
# apps/user_service/app/dependencies/audit_logs/audit_logger.py

from typing import Dict, Any, Optional, List
import hashlib
import json
import asyncio
import logging
from datetime import datetime, timezone
from dataclasses import dataclass
from fastapi import Request
import asyncpg

logger = logging.getLogger(__name__)


@dataclass
class AuditEventData:  # pylint: disable=too-many-instance-attributes
    """Data class for audit event information."""

    user_context: dict
    action_type: str
    data_classification: str
    table_name: str
    record_id: Optional[str]
    old_values: Optional[Dict]
    new_values: Optional[Dict]
    changed_fields: Optional[List[str]]
    compliance_tags: List[str]
    risk_level: str
    description: str
    status_code: Optional[int] = None
    category: Optional[str] = None


class AuditLogger:  # pylint: disable=too-many-instance-attributes
    """
    Simplified audit logger aligned with RBAC Audit Values Guide.
    Optimized for single-core processing with structured audit data.
    """

    def __init__(self):
        self._queue = asyncio.Queue(maxsize=500)
        self._processing_task = None
        self._last_hash = None
        self._shutdown_event = asyncio.Event()
        self._db_pool = None

        # Processing configuration
        self._batch_size = 10
        self._batch_timeout = 3.0
        self._max_retries = 3

    async def start_processing(self, db_pool):
        """
        Start the audit processing task with the provided database pool.

        Args:
            db_pool: Database connection pool for audit log storage
        """
        if self._processing_task is None:
            self._db_pool = db_pool
            self._processing_task = asyncio.create_task(
                self._process_audit_queue(db_pool)
            )
            print("Audit processing started")

    async def shutdown(self):
        """
        Gracefully shutdown the audit processing task.

        Waits for the processing task to complete with a timeout,
        then cancels it if necessary.
        """
        print("Shutting down audit processing...")
        self._shutdown_event.set()

        if self._processing_task:
            try:
                await asyncio.wait_for(self._processing_task, timeout=10.0)
            except asyncio.TimeoutError:
                print("Audit processing shutdown timeout")
                self._processing_task.cancel()

    async def log_audit_event(self, event_data: AuditEventData, request: Request):
        """
        Log an audit event with the provided data.

        Args:
            event_data: AuditEventData object containing all audit information
            request: FastAPI Request object for extracting client information
        """
        try:
            audit_event = self._create_audit_event_dict(event_data, request)
            print("ADDING IN QUEUE log_audit_event")

            try:
                self._queue.put_nowait(audit_event)
            except asyncio.QueueFull:
                try:
                    await asyncio.wait_for(self._queue.put(audit_event), timeout=0.1)
                except asyncio.TimeoutError:
                    print(f"Audit queue full, dropping {event_data.action_type} event")

        except (ValueError, TypeError, KeyError) as e:
            print(f"Audit logging error - invalid data: {e}")
        except (asyncio.QueueFull, asyncio.TimeoutError) as e:
            print(f"Audit logging error - queue issue: {e}")
        except Exception as e:  # pylint: disable=broad-except
            print(f"Audit logging unexpected error: {e}")
            logger.error("Unexpected error in audit logging: %s", e, exc_info=True)

    def _create_audit_event_dict(
        self,
        event_data: AuditEventData,
        request: Request,
    ) -> Dict[str, Any]:
        """
        Create the audit event dictionary from AuditEventData.

        Args:
            event_data: AuditEventData object containing audit information
            request: FastAPI Request object

        Returns:
            Dict containing the formatted audit event
        """
        return {
            "organization_id": event_data.user_context.get("organization_id"),
            "user_id": event_data.user_context.get("user_id"),
            "user_email": event_data.user_context.get("user_email", "unknown"),
            "user_role": event_data.user_context.get("user_role", "unknown"),
            "action_type": event_data.action_type,
            "data_classification": event_data.data_classification,
            "table_name": event_data.table_name,
            "record_id": event_data.record_id,
            "old_values": event_data.old_values,
            "new_values": event_data.new_values,
            "changed_fields": event_data.changed_fields or [],
            "compliance_tags": event_data.compliance_tags,
            "risk_level": event_data.risk_level,
            "ip_address": self._get_client_ip(request),
            "description": event_data.description,
            "timestamp": datetime.now(timezone.utc),
            "status_code": event_data.status_code,
            "category": event_data.category,
        }

    async def _process_audit_queue(self, db_pool):
        batch = []
        consecutive_empty_batches = 0

        while not self._shutdown_event.is_set():
            try:
                timeout = 10.0 if consecutive_empty_batches > 3 else self._batch_timeout

                try:
                    event = await asyncio.wait_for(self._queue.get(), timeout=timeout)
                    batch.append(event)
                    consecutive_empty_batches = 0

                    while len(batch) < self._batch_size:
                        try:
                            event = self._queue.get_nowait()
                            batch.append(event)
                        except asyncio.QueueEmpty:
                            break

                except asyncio.TimeoutError:
                    consecutive_empty_batches += 1

                if batch:
                    print("PROCESSING AUDIT LOGS")
                    await self._write_audit_batch_with_retry(db_pool, batch)
                    batch.clear()
                    await asyncio.sleep(5)

            except (asyncio.CancelledError, asyncio.TimeoutError) as e:
                print(f"Audit processing interrupted: {e}")
                break
            except (OSError, RuntimeError) as e:
                print(f"System error processing audit batch: {e}")
                logger.error(
                    "System error processing audit batch: %s", e, exc_info=True
                )
                await asyncio.sleep(1)
            except Exception as e:  # pylint: disable=broad-except
                print(f"Error processing audit batch: {e}")
                logger.error("Error processing audit batch: %s", e, exc_info=True)
                await asyncio.sleep(1)

        if batch:
            try:
                await self._write_audit_batch_with_retry(db_pool, batch)
            except (asyncpg.PostgresError, ConnectionError) as e:
                print(f"Failed to write final audit batch (database error): {e}")
                logger.error(
                    "Failed to write final audit batch (database error): %s",
                    e,
                    exc_info=True,
                )
            except Exception as e:  # pylint: disable=broad-except
                print(f"Failed to write final audit batch: {e}")
                logger.error("Failed to write final audit batch: %s", e, exc_info=True)

    async def _write_audit_batch_with_retry(self, db_pool, events: List[Dict]):
        for attempt in range(self._max_retries):
            try:
                await self._write_audit_batch(db_pool, events)
                return
            except (asyncpg.PostgresError, ConnectionError) as e:
                print(f"Audit write attempt {attempt + 1} failed (database error): {e}")
                if attempt < self._max_retries - 1:
                    await asyncio.sleep(2**attempt)
                else:
                    print(
                        f"Failed to write {len(events)} audit events after "
                        f"{self._max_retries} attempts"
                    )
                    logger.error(
                        "Failed to write audit events after %d attempts: %s",
                        self._max_retries,
                        e,
                        exc_info=True,
                    )
            except (OSError, RuntimeError) as e:
                print(f"Audit write attempt {attempt + 1} failed (system error): {e}")
                logger.error(
                    "System error in audit write attempt %d: %s",
                    attempt + 1,
                    e,
                    exc_info=True,
                )
                if attempt < self._max_retries - 1:
                    await asyncio.sleep(2**attempt)
                else:
                    print(
                        f"Failed to write {len(events)} audit events after "
                        f"{self._max_retries} attempts"
                    )
            except Exception as e:  # pylint: disable=broad-except
                print(
                    f"Audit write attempt {attempt + 1} failed (unexpected error): {e}"
                )
                logger.error(
                    "Unexpected error in audit write attempt %d: %s",
                    attempt + 1,
                    e,
                    exc_info=True,
                )
                if attempt < self._max_retries - 1:
                    await asyncio.sleep(2**attempt)
                else:
                    print(
                        f"Failed to write {len(events)} audit events after "
                        f"{self._max_retries} attempts"
                    )

    async def _get_last_hash_from_db(self, db_pool) -> Optional[str]:
        """
        Fetch the last hash from the database to maintain audit chain integrity.

        Returns:
            Optional[str]: The last hash from the database, or None if no audit logs exist
        """
        try:
            async with db_pool.acquire() as conn:
                query = """
                    SELECT hash_signature 
                    FROM public.audit_logs 
                    ORDER BY timestamp DESC, id DESC 
                    LIMIT 1
                """

                result = await conn.fetchrow(query)
                return result["hash_signature"] if result else None
        except (asyncpg.PostgresError, ConnectionError) as e:
            print(f"Error fetching last hash from database: {e}")
            logger.error("Database error fetching last hash: %s", e, exc_info=True)
            return None
        except Exception as e:  # pylint: disable=broad-except
            print(f"Unexpected error fetching last hash from database: {e}")
            logger.error("Unexpected error fetching last hash: %s", e, exc_info=True)
            return None

    async def _write_audit_batch(self, db_pool, events: List[Dict]):
        if not events:
            return

        async with db_pool.acquire() as conn:
            try:
                # Get the last hash from database if we don't have it cached
                if self._last_hash is None:
                    self._last_hash = await self._get_last_hash_from_db(db_pool)

                insert_query = """
                    INSERT INTO audit_logs (
                        organization_id, user_id, user_email, user_role,
                        action_type, data_classification, table_name, record_id,
                        old_values, new_values, changed_fields,
                        compliance_tags, risk_level,
                        ip_address,
                        timestamp, hash_signature, previous_hash,
                        description, retention_date, status_code, category
                    ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
                              $9, $10, $11, $12, $13, $14,
                              $15, $16, $17, $18, $19, $20, $21)
                """

                batch_data = []
                for event in events:
                    hash_signature = self._generate_hash(event)
                    retention_date = self._calculate_retention_date(
                        event["timestamp"], event["data_classification"]
                    )

                    batch_data.append(
                        (
                            event["organization_id"],
                            event["user_id"],
                            event["user_email"],
                            event["user_role"],
                            event["action_type"],
                            event["data_classification"],
                            event["table_name"],
                            event["record_id"],
                            (
                                json.dumps(event["old_values"])
                                if event["old_values"]
                                else None
                            ),
                            (
                                json.dumps(event["new_values"])
                                if event["new_values"]
                                else None
                            ),
                            (
                                event["changed_fields"]
                                if event["changed_fields"]
                                else None
                            ),
                            (
                                event["compliance_tags"]
                                if event["compliance_tags"]
                                else None
                            ),
                            event["risk_level"],
                            event["ip_address"],
                            event["timestamp"],
                            hash_signature,
                            self._last_hash,
                            event["description"],
                            retention_date,
                            event.get("status_code"),
                            event.get("category"),
                        )
                    )
                    self._last_hash = hash_signature

                await conn.executemany(insert_query, batch_data)
                print(f"Successfully wrote {len(events)} audit events")
                print(f"AUDIT LOGS: Successfully wrote {len(events)} audit events")
            except (asyncpg.PostgresError, ConnectionError) as e:
                print(f"Database write error: {e}")
                logger.error("Database write error: %s", e, exc_info=True)
                raise
            except Exception as e:  # pylint: disable=broad-except
                print(f"Unexpected database write error: {e}")
                logger.error("Unexpected database write error: %s", e, exc_info=True)
                raise

    def _generate_hash(self, event: Dict) -> str:
        hash_data = (
            f"{event['organization_id']}"
            f"{event['user_id']}"
            f"{event['action_type']}"
            f"{event['timestamp'].isoformat()}"
            f"{event['description']}"
        )
        if self._last_hash:
            hash_data += self._last_hash

        return hashlib.sha256(hash_data.encode()).hexdigest()

    def _calculate_retention_date(
        self, timestamp: datetime, data_classification: str
    ) -> datetime:
        retention_years = {
            "phi": 7,
            "pii": 7,
            "financial": 7,
            "general": 3,
            "public": 1,
        }.get(data_classification, 3)

        return timestamp.replace(year=timestamp.year + retention_years)

    def _get_client_ip(self, request: Request) -> str:
        forwarded_for = request.headers.get("x-forwarded-for")
        if forwarded_for:
            return forwarded_for.split(",")[0].strip()

        real_ip = request.headers.get("x-real-ip")
        if real_ip:
            return real_ip

        return (
            getattr(request.client, "host", "unknown") if request.client else "unknown"
        )

    def get_queue_stats(self) -> Dict[str, Any]:
        """
        Get current statistics about the audit queue and processing status.

        Returns:
            Dict[str, Any]: Dictionary containing queue statistics including:
                - queue_size: Current number of items in the queue
                - max_queue_size: Maximum capacity of the queue
                - processing_active: Whether the processing task is active
                - shutdown_requested: Whether shutdown has been requested
        """
        return {
            "queue_size": self._queue.qsize(),
            "max_queue_size": self._queue.maxsize,
            "processing_active": self._processing_task
            and not self._processing_task.done(),
            "shutdown_requested": self._shutdown_event.is_set(),
        }


# Singleton
audit_logger = AuditLogger()
