# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "notification_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1anotification_service.proto\x12\x0cnotification"(\n\x13NotificationRequest\x12\x11\n\tbody_data\x18\x01 \x01(\t"$\n\x11NotificationReply\x12\x0f\n\x07message\x18\x01 \x01(\t2c\n\x07Greeter\x12X\n\x10SendNotification\x12!.notification.NotificationRequest\x1a\x1f.notification.NotificationReply"\x00\x42y\n!io.grpc.examples.pushnotificationB\x10pushnotificationP\x01Z:notification-service/gen/proto/notification;notificationpb\xa2\x02\x03HLWb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "notification_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n!io.grpc.examples.pushnotificationB\020pushnotificationP\001Z:notification-service/gen/proto/notification;notificationpb\242\002\003HLW"
    _globals["_NOTIFICATIONREQUEST"]._serialized_start = 44
    _globals["_NOTIFICATIONREQUEST"]._serialized_end = 84
    _globals["_NOTIFICATIONREPLY"]._serialized_start = 86
    _globals["_NOTIFICATIONREPLY"]._serialized_end = 122
    _globals["_GREETER"]._serialized_start = 124
    _globals["_GREETER"]._serialized_end = 223
# @@protoc_insertion_point(module_scope)
